### ISSUE TITLE
Couldn't find an email

### ISSUE THREAD

**Issue by jeremycherfas** [cmadland/phd#14]
So using this. When I went to `https://grav.madland.ca/blog/keeping-track` I got the Grav error

````
0 - An exception has been thrown during the rendering of a template ("Template "twitterfeed.html.twig" is not defined.").
````

I'm trying to find out how other people have used the gitsync plugin, and you had a write-up that appeared din a search. I will look on the site now.

**Comment by cmadland** [comment]
HI @jeremycherfas I did some cleanup of the site. You might be looking for https://grav.madland.ca/blog/git-grav-nerdery

**Comment by jeremycherfas** [comment]
Thanks. In the interim, I tried again, and again git-sync plugin did
some very weird things, not least deleting all themes except Quark,
which left me completely unable to access anything.
Hey ho; back to rolling my own solution, I guess.


On Tue, 12 Feb 2019, at 12:26 AM, Colin Madland wrote:
> HI @jeremycherfas[1] I did some cleanup of the site. You might be
> looking for https://grav.madland.ca/blog/git-grav-nerdery> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].

Links:

  1. https://github.com/jeremycherfas
  2. https://github.com/cmadland/phd/issues/14#issuecomment-462537310

**Comment by cmadland** [comment]
Hang on, that error about the Twitterfeed was on your site? I've had that before. You can either create the TWIG template (I couldn't figure out how to do that) or delete the 'Twitter Feed' page from your site.

For GitSync to work, you need to start with a fresh git repo with only a README and no commits.

**Comment by jeremycherfas** [comment]
No, the error then was on your site, and I wanted to alert you to it. Obviously you fixed it. I wanted to read about how you had used git-sync, to see where I had gone wrong.

The thing that puzzles me, I suppose, is that the instructions do not actually say that you have to start with a fresh repo. I've been very happy using a local site to create new posts and then pushing to github and have a hook push to the live site. Now I'm getting closer to using micropub to create at least some note-type posts direct on the live site, and for that I was hoping to be able to use git-sync to bring everything back to the github repo, from which I could fetch to my local version.

I now think it is going to be simpler all around to work the commit and push into the micropub flow.

**Comment by cmadland** [comment]
Thanks for the heads up!

I've been very pleased with gitsync and have it active on several Grav sites. It allows me to compose in Atom and push to GitHub which automatically syncs with Grav. It's seamless.

You are correct, the instructions in the Wizard aren't clear that you should use a fresh repo.

![image](https://user-images.githubusercontent.com/12282929/52677988-f2a79180-2ee4-11e9-9018-abae6728ebf9.png)

I've pinged @paulhibbitts who helped develop the plugin.

**Comment by cmadland** [comment]
Looks like Paul has initiated a PR to get the instructions updated.
