### ISSUE TITLE
Idea from CSSHE regarding data sources and authenticity 

### ISSUE THREAD

**Issue by mpaskevi** [cmadland/phd#28]
The comment regarding you representing Indigenous populations in your research or through your interpretation of the data was critical. Perhaps you could design your study so that the voices of your participants are maintained by making the source audio recordings openly accessible, or by presenting them as podcasts in a collection, etc.

**Comment by cmadland** [comment]
This is a great point, @mpaskevi I do think that there is a critical need to bring Indigenous voices to the forefront of this.
